# Generated by Django 5.2.4 on 2025-09-11 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_editora_livro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editora',
            old_name='cpj',
            new_name='cnpj',
        ),
    ]
