# Generated by Django 5.2.5 on 2025-09-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_cpj_editora_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='dimensoes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
